name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
    

jobs:

  npm-security-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - name: Copy the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x ${{matrix.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - name: Start Audit script
      run: npm run sec-test-npm

  integration-tests:
    runs-on: ubuntu-latest
    needs: npm-security-test
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - name: Copy the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x ${{matrix.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - name: Install the dependencies
      run: npm install
    - name: Start tests
      run: npm test
 
  deploy:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true